
# Flexible Robotic Arm Task1: from a desired quasi-step state-input curve (that evolves from one equilibrium to
# another) to an optimal trajectory thanks to the regularized Newton's Like Method (in its closed-loop version)

from parameters import ns, ni
from numpy import pi, array, column_stack, eye
from equilibria import searchFRAInputGivenAnEquilibria
from curves import generateCurves, CurveType
from dynamics import discretizedDynamicFRA as discretizedDynamicFuntion
from methods import runNewtonMethodTrkTrj

from matplotlib import pyplot
from numpy import linspace, squeeze
from parameters import discretizationStep as dt

def task1():

    # Definition of the time instants in which the desired input-state curve will evolve.
    T = array([0, 4, 8, 12])

    # Defining the desired input-state curve (a sigmoid-junction between two symmetric equilibrium points).
    # Notice: the input curve is generated by considering the angle of the first link of the FRA (at each
    # time instant) and by searching the corresponding input value that leads to the equilibrium in which
    # the second link is pointing downwards (alias at the same angle but with opposite sign).
    swingingAngle = 120 # value in degrees
    angle = pi/180*swingingAngle/2
    xx_equilibrium1 = array([angle,-angle,0,0])
    xx_equilibrium2 = array([-angle,angle,0,0])
    xx_des, t = generateCurves(
        column_stack((xx_equilibrium1, xx_equilibrium1, xx_equilibrium2, xx_equilibrium2)), None,
        T, CurveType.sigmoid
    )
    uu_des = array([searchFRAInputGivenAnEquilibria(xx_des[0,i]) for i in range(len(t))]).reshape(1, len(t))

    # Notice that in the case we want simple steps as desired curve we can simply use the following code:
    # xx_des[:,:int(tx.size/2)] = xx_equilibrium1.reshape(ns,1)
    # xx_des[:,int(tx.size/2):] = xx_equilibrium2.reshape(ns,1)
    # uu_des[:int(tu.size/2)] = uu_equlibrium1.reshape(ni,1)
    # uu_des[int(tu.size/2):] = uu_equlibrium2.reshape(ni,1)

    # Defining cost matrices (for a trajectory tracking optimization probl0.001em) and applying the Newton Method
    QQ = 12*eye(ns)
    RR = 0.001*eye(ni)
    newtonMethodMaxIterations = 20
    trjTrkOCPData = runNewtonMethodTrkTrj(
        xx_des, uu_des, xx_equilibrium1, newtonMethodMaxIterations,
        discretizedDynamicFuntion, 1e-6,
        QQ, RR
    )

    return trjTrkOCPData

if __name__ == "__main__": task1()
