
# Collection of functions that implement the Tegulators used in the Project (and correlated functions)

from miscellaneous import correctStateInputCurvesShapes
from numpy import zeros, std, random, max, abs, array
from cvxpy import Variable, Minimize, Problem, quad_form, OSQP
from solver import solveLQP

def runLQRController(xx_traj, uu_traj, KK, discretizedDynamicFunction, xx0Noise = None, includeMeasureNoises = False):
    """
    Run the LQR controller (using the given feedback gain KK) on the given trajectory.
    Arguments:
    - xx_traj: The state reference trajectory
    - uu_traj: The input reference trajectory
    - KK: The feedback gain matrix (related to the LQR)
    - discretizedDynamicFunction: A function that represents the discretized dynamic of the system
    - xx0Noise: A noise to be eventually added to the initial state
    - includeMeasureNoises: A boolean flag that indicates if the measure noises should be included in the simulation
                            In case, noises are added to the state trajectory at each time instant, where for each state the
                            noise is generated by taking samples from a N(0,1) normal distribution scaled by a percentage of
                            the maximum value assumed by the state itself along the trajectory.
    Returns:
    - xx_track: The state trajectory tracked by the LQR controller
    - uu_track: The input trajectory applied by the LQR controller
    """
    xx_traj, uu_traj, ns, ni, TT = correctStateInputCurvesShapes(xx_traj, uu_traj)
    xx_track = zeros((ns, TT))
    uu_track = zeros((ni, TT))

    if includeMeasureNoises:
        xx_traj_maxs = max(abs(xx_traj), axis=1)
        percentage = 0.0005
        xx_traj_noise_std = percentage*xx_traj_maxs

    xx_track[:,0] = xx_traj[:,0] + (xx0Noise if xx0Noise is not None else zeros(ns))

    for tt in range(TT-1): 
        # Evolving the dynamic of the system using the LQR (in a closed loop fashion)
        uu_track[:,tt] = uu_traj[:, tt] + KK[:,:,tt]@(xx_track[:,tt] - xx_traj[:,tt])
        xx_track[:,tt+1] = discretizedDynamicFunction(xx_track[:,tt], uu_track[:,tt], onlyZeroOrderDynamic = True)

        if includeMeasureNoises:
            noises = [random.normal(loc = 0.0, scale = sc, size = 1) for sc in xx_traj_noise_std]
            xx_track[:,tt+1] += array(noises).squeeze()

    return xx_track, uu_track

def runMPController(xx_traj, uu_traj, AA, BB, QQ, RR, QQT, MPC_TT, discretizedDynamicFunction, xx0Noise = None, relyOnCVX = False, includeMeasureNoises = False): 
    """
    Run the MPC controller on the given trajectory.
    Arguments:
    - xx_traj: The state reference trajectory
    - uu_traj: The input reference trajectory
    - AA: Matrix A (alias obtained deriving w.r.t. the state) of the linearized dynamics around the reference trajectory (T.V.)
    - BB: Matrix B (alias obtained deriving w.r.t. the input) of the linearized dynamics around the reference trajectory (T.V.)
    - QQ, RR, QQT: Cost matrices (supposed to be time invariant)
    - MPC_TT: Prediction time horizon for the MPC (in terms of quantity of time instants)
    - discretizedDynamicFunction: A function that represents the discretized dynamic of the system
    - xx0Noise: A noise to be eventually added to the initial state
    - relyOnCVX: A boolean flag that indicates if the cvxpy library should be used to solve the LQ problems involved in the MPC action
    - includeMeasureNoises: A boolean flag that indicates if the measure noises should be included in the simulation
                            In case, noises are added to the state trajectory at each time instant, where for each state the
                            noise is generated by taking samples from a N(0,1) normal distribution scaled by a percentage of
                            the maximum value assumed by the state itself along the trajectory.
    Returns:
    - xx_track: The state trajectory tracked by the MPC controller
    - uu_track: The input trajectory applied by the MPC controller
    """
    xx_traj, uu_traj, ns, ni, TT = correctStateInputCurvesShapes(xx_traj, uu_traj)
    xx_track = zeros((ns, TT))
    uu_track = zeros((ni, TT))

    if includeMeasureNoises:
        xx_traj_maxs = max(abs(xx_traj), axis=1)
        percentage = 0.0005
        xx_traj_noise_std = percentage*xx_traj_maxs

    xx_track[:,0] = xx_traj[:,0] + (xx0Noise if xx0Noise is not None else 0)

    for tt in range(TT-MPC_TT-1): 
        xxt = xx_track[:,tt]
        if not relyOnCVX:
            KK = solveLQP(AA[:,:,tt:tt+MPC_TT], BB[:,:,tt:tt+MPC_TT], QQ, RR, QQT, MPC_TT, xxt)[0]
            uu_track[:,tt] = uu_traj[:, tt] + KK[:,:,0]@(xx_track[:,tt] - xx_traj[:,tt])
        else:
            uu_track[:,tt] = solveConstraintLQPCVX(
                xxt, xx_traj[:,tt:tt+MPC_TT], uu_traj[:,tt:tt+MPC_TT],
                AA[:,:,tt:tt+MPC_TT], BB[:,:,tt:tt+MPC_TT], QQ, RR, QQT, MPC_TT
            )[2]
        xx_track[:,tt+1] = discretizedDynamicFunction(xx_track[:,tt], uu_track[:,tt], onlyZeroOrderDynamic = True)

        if includeMeasureNoises:
            noises = [random.normal(loc = 0.0, scale = sc, size = 1) for sc in xx_traj_noise_std]
            xx_track[:,tt+1] += array(noises).squeeze()
    
    return xx_track, uu_track

def solveConstraintLQPCVX(xxt, xx_des, uu_des, AA, BB, QQ, RR, QQT, TT):
    """
    This method is eventually used in couple with the method "runMPController" to solve the LQ problems involved in the
    MPC action by the use of cvxpy library (and not by the use of the solver.solveLQP method). This is relevant in case
    it is needed to introduce additional constraints (w.r.t the initial state and the dynamic itself) to the problem.
    In that case, these constraints can indeed be easily added by the use of cvxpy library (AND they are gonna to be
    added direct in this method).
    Arguments:
    - xxt: The initial state at time t
    - xx_des: The state reference desired trajectory
    - uu_des: The input reference desired trajectory
    - AA: Matrix A (alias obtained deriving w.r.t. the state) of the linearized dynamics around the reference trajectory (T.V.)
    - BB: Matrix B (alias obtained deriving w.r.t. the input) of the linearized dynamics around the reference trajectory (T.V.)
    - QQ, RR, QQT: Cost matrices (supposed to be time invariant)
    - TT: Number of time instants of the evolution of xx_des and uu_des
    Returns:
    - uu: The optimal input trajectory
    - xx: The optimal state trajectory
    - inputActionFirstValue: The first value of the optimal input trajectory
    """
    xx_des, uu_des, ns, ni, _ = correctStateInputCurvesShapes(xx_des, uu_des)
    xxt = xxt.squeeze()

    # Definition of problem decision variables
    xx = Variable((ns, TT))
    uu = Variable((ni, TT))
    # Definition of cost function and constraints variables
    cost = 0
    constr = []
    # Definition the initial condition constraint
    constr += [xx[:,0] == xxt]
    # Definition of the stage cost functions and the equality constraints related to the linearized dynamics
    for tt in range(TT-1): 
        cost += quad_form((xx[:,tt]-xx_des[:,tt]), QQ) + quad_form((uu[:,tt]-uu_des[:,tt]), RR)
        constr += [xx[:,tt+1] == AA[:,:,tt]@xx[:,tt] + BB[:,:,tt]@uu[:,tt]]
    # Definition of the terminal cost function
    cost += quad_form((xx[:,TT-1] - xx_des[:,TT-1]), QQT)

    # Solving the MPC problem
    problem = Problem(Minimize(cost), constr)
    problem.solve(solver = OSQP, eps_abs=1e-9, eps_rel=1e-9)
    if problem.status in ["infeasible", "infeasible_inaccurate"]: raise RuntimeError("Unfeasible MPC problem!")
    inputActionFirstValue = uu[:,0].value
    return uu.value, xx.value, inputActionFirstValue

def generateInitialStateNoise(xx, noiseStdPercentage, gainK = 2, randomNumberGenerator = None):
    """
    Generation of a noise to be added to the initial state of the system.
    That noise in generated (for each single state) by taking samples from a N(0,1) normal distribution
    scaled in its standard deviation by the percentage of the standard deviation of the state itself.
    """
    ns = xx.shape[0]
    if not noiseStdPercentage or noiseStdPercentage <= 0: return zeros(ns)

    # Fix a local r.n.g. related to a local seed in order to generate the same noise (in the various Tasks)
    if randomNumberGenerator is None: randomNumberGenerator = random.default_rng(2828)  

    # Compute the standard deviation for each state (row-wise)
    stateSD = std(xx, axis = 1)
    # Scale the standard deviation by the percentage
    noiseSD = gainK*stateSD*noiseStdPercentage
    
    # Generate (and return) a Gaussian noise with personalized standard deviation taking
    # samples from a N(0,1) normal distribution and scaling them by noiseStdPercentage
    return randomNumberGenerator.normal(loc = 0.0, scale = noiseSD, size = ns)
